name: Test Documentation Snippets

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    # allow this workflow to be triggered manually

jobs:
  run_md:
    name: 'Execute inline D snippets from docs markdown files'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code and submodules 
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up D compiler / tools
        uses: dlang-community/setup-dlang@v1.1.0
        with:
          compiler: dmd-latest
      - name: Fetch 'md' tool
        run: dub fetch md@0.5.0-beta
      - name: Test custom-formats.md
        run: dub run md -- docs-src/custom-formats.md
