name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja

    - name: D Compiler Installation
      uses: mihails-strasuns/setup-dlang@v1.1.1
      with:
        compiler: ${{ matrix.dc }}
      
    - name: Test
      run: |
       dub test --config=std
